export { default as NewPlayer } from './new-player/new-player.component'
export { default as Header } from './header/header.component'
export { default as Player } from './player/player.component'
export { default as Playground } from './playground/playground.component'
export { default as Main } from './main/main.component'
export { default as Cards } from './cards/cards.component'
export { default as Stats } from './stats/stats.component'
export { default as Invite } from './invite/invite.component'
